version: "4.0"

services:
    main-mongo:
        image: mongo:6.0.8-jammy
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=root
        ports:
            - '27017:27017'
        volumes:
            - main-mongo-storage:/var/lib/mongo/data
        networks:
            - main-network

networks:
    main-network:

volumes:
    main-mongo-storage: